#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

echo "======================================================="
echo "   Standalone Kasm Workspaces Installer"
echo "======================================================="
echo ""

# Capture the actual user running the script
CURRENT_USER=${SUDO_USER:-$USER}

# 1. Detect Base Domain from the running Traefik Swarm service
echo "--> Detecting Base Domain from Traefik..."
DETECTED_DOMAIN=$(sudo docker service inspect proxy_traefik --format '{{range .Spec.TaskTemplate.ContainerSpec.Env}}{{println .}}{{end}}' 2>/dev/null | grep '^BASE_DOMAIN=' | cut -d '=' -f2 || true)

if [ -n "$DETECTED_DOMAIN" ]; then
    echo "✅ Detected Base Domain: $DETECTED_DOMAIN"
    echo ""
    KASM_SUBDOMAIN=""
    while [ -z "$KASM_SUBDOMAIN" ]; do
        read -p "Enter the subdomain prefix for Kasm (e.g., 'kasm' to create kasm.${DETECTED_DOMAIN}): " KASM_SUBDOMAIN
        if [ -z "$KASM_SUBDOMAIN" ]; then
            echo "❌ Error: Subdomain cannot be empty."
        fi
    done
    KASM_DOMAIN="${KASM_SUBDOMAIN}.${DETECTED_DOMAIN}"
else
    echo "⚠️ Could not automatically detect Base Domain."
    KASM_DOMAIN=""
    while [ -z "$KASM_DOMAIN" ]; do
        read -p "Enter the fully qualified domain for Kasm (e.g., kasm.app.dsolutiontech.net): " KASM_DOMAIN
        if [ -z "$KASM_DOMAIN" ]; then
            echo "❌ Error: Domain cannot be empty."
        fi
    done
fi

echo "--> Kasm will be routed to: https://${KASM_DOMAIN}"

# 2. Select Host IP Address
echo ""
echo "--> Configuring Internal Routing IP..."
echo "Here are your current IP addresses:"
hostname -I | tr ' ' '\n' | grep -v '^$'
echo ""

HOST_IP=""
while [ -z "$HOST_IP" ]; do
    read -p "Enter the IP address of this node where Kasm will be installed: " HOST_IP
    if [ -z "$HOST_IP" ]; then
        echo "❌ Error: IP Address cannot be empty."
    fi
done

# 3. Generate Isolated Kasm Routing Configuration
echo ""
echo "--> Generating isolated routing configuration for Kasm..."

# Write the routing logic and Kasm-specific middlewares directly into kasm.yml
cat << EOF | sudo tee /opt/proxy/traefik-dynamic/kasm.yml > /dev/null
http:
  middlewares:
    # --- Kasm-Specific Headers (moderate security) ---
    kasm-secure-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        forceSTSHeader: true
        customFrameOptionsValue: "SAMEORIGIN"
        contentTypeNosniff: true
        referrerPolicy: "strict-origin-when-cross-origin"

  routers:
    kasm-router:
      rule: Host(\`${KASM_DOMAIN}\`)
      entryPoints: [ websecure ]
      tls: { certResolver: le-dns }
      middlewares: [ kasm-secure-headers ]
      service: kasm-svc

  services:
    kasm-svc:
      loadBalancer:
        serversTransport: kasm-selfsigned-tls
        servers:
          - url: "https://${HOST_IP}:8443"

  # Transport for self-signed upstream
  serversTransports:
    kasm-selfsigned-tls:
      insecureSkipVerify: true
      forwardingTimeouts:
        dialTimeout: 5s
        responseHeaderTimeout: 60s
        idleConnTimeout: 90s
EOF

# Apply proper permissions
sudo chown "$CURRENT_USER":"$CURRENT_USER" /opt/proxy/traefik-dynamic/kasm.yml
sudo chmod 644 /opt/proxy/traefik-dynamic/kasm.yml
echo "Traefik route created at /opt/proxy/traefik-dynamic/kasm.yml"

# 4. Download and Install Kasm Workspaces
echo ""
echo "--> Starting Kasm Workspaces installation..."
cd /tmp

# Clean up any failed/corrupted downloads
sudo rm -f kasm_release*.tar.gz
sudo rm -rf kasm_release

# Download the official Kasm 1.18.1 release
curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.18.1.tar.gz
tar -xf kasm_release_1.18.1.tar.gz

# Run the installer on port 8443 and automatically accept the EULA
sudo bash kasm_release/install.sh -L 8443 --accept-eula

echo ""
echo "======================================================="
echo "✅ Kasm Workspaces Installation Complete!"
echo "======================================================="
echo "Traefik is now routing traffic from https://${KASM_DOMAIN} to Kasm on port 8443."
echo "⚠️ IMPORTANT: Please scroll up and copy the Default Admin Credentials generated by the Kasm installer!"
